name: "gh-secrets-shipper"

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    name: "gh-secrets-shipper"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      KMS_KEY_ID:  ${{ secrets.KMS_KEY_ID }}
      BUCKET: ${{ secrets.S3_SECRETS_BUCKET }}

    steps:
      - name: Create datakey
        id: dk
        run: |
          plain_datakey=$(openssl rand --base64 32)
          echo "::add-mask::$plain_datakey"
          echo "plain_datakey=$plain_datakey" >> "$GITHUB_OUTPUT"

      - name: Encrypt secrets
        id: encrypt
        run: |
          plain_secrets=$(echo '${{ toJson(secrets) }}')
          enc_secrets=$(echo $plain_secrets | gpg --batch --passphrase $PLAIN_DATAKEY --no-symkey-cache \
            --symmetric --cipher-algo AES256 | base64 -w0)
          echo "::add-mask::$enc_secrets"
          echo "enc_secrets=$enc_secrets" >> "$GITHUB_OUTPUT"
        env:
          PLAIN_DATAKEY: ${{ steps.dk.outputs.plain_datakey }}

      - name: Upload to S3
        run: |
          enc_datakey=$(aws kms encrypt --key-id $KMS_KEY_ID --plaintext $PLAIN_DATAKEY \
            --query CiphertextBlob --output text)
          echo $enc_datakey | aws s3 cp - s3://$BUCKET/${{ github.event.repository.name }}/secrets.key
          echo $ENC_SECRETS | aws s3 cp - s3://$BUCKET/${{ github.event.repository.name }}/secrets
        env:
          PLAIN_DATAKEY: ${{ steps.dk.outputs.plain_datakey }}
          ENC_SECRETS: ${{ steps.encrypt.outputs.enc_secrets }}
