name: "gh-secret-shipper"

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    name: "gh-secret-shipper"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      KMS_KEY_ID:  ${{ secrets.KMS_KEY_ID }}
      BUCKET: ${{ secrets.S3_BUCKET }}

    steps:
      - name: Encrypt
        id: encrypt
        run: |
          plaintext=$(echo '${{ toJson(secrets) }}' | base64 -w0)
          blob=$(aws kms encrypt --key-id $KMS_KEY_ID --plaintext $plaintext \
            --query CiphertextBlob --output text)
          echo "blob=$blob" >> "$GITHUB_OUTPUT"

      - name: S3
        run: |
          echo $BLOB | aws s3 cp - s3://$BUCKET/${{ github.event.repository.name }}/secrets
        env:
          BLOB: ${{ steps.encrypt.outputs.blob }}
